version: "3"

services:
  perrapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: perrApp
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - data_images:/pictureFiles
    networks:
      - dataBaseNetwork

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ## Если требуется открыть порт для доступа к базе данных
    ##ports:
    ##  - "5554:5432"
    volumes:
      - data_db:/var/lib/postgresql/data
    networks:
      - dataBaseNetwork
    restart: always

networks:
  dataBaseNetwork:
    driver: bridge

volumes:
  data_db:
  data_images: