server:
  type: port
  port: 8080

postgresConfigDb:
  username: postgres
  password: postgres
  host: 0.0.0.0
  port: 5555
  dbname: postgres
  sslmode: disable
  max-attempts-for-connection: 10
  make-start-tables: true
  make-start-admin: true