server:
  type: port
  port: 8080

postgresConfigDb:
  username: postgres
  password: mysecretpassword
  host: 0.0.0.0
  port: 5342
  dbname: postgres
  sslmode: disable
  max-attempts-for-connection: 10
  make-start-tables: true